### ISSUE TITLE
meanposition intepretation

### ISSUE THREAD

**Issue by Yijun-Tian** [XinDong9511/mdseqpos_py3#1]
Hello Xindong,
Could you give more specifications about the "meanposition" in motif.py? Is it a relative position according to each peak? Does meanposition=0.5 mean the motif in the center of a peak?
Thank you,
Yijun

**Comment by xindongnov** [comment]
Hi @Yijun-Tian ,

It's the mean of relative position to the summit(center) of the peaks. But mean position = 0 is the center. So the value range will be [-0.5, 0.5].

Hope this solves your problem.

**Comment by Yijun-Tian** [comment]
> Hi @Yijun-Tian ,
> 
> It's the mean of relative position to the summit(center) of the peaks. But mean position = 0 is the center. So the value range will be [-0.5, 0.5].
> 
> Hope this solves your problem.
Thanks for the answer, Xin.
