### ISSUE TITLE
Mean_position always negative value

### ISSUE THREAD

**Issue by Yijun-Tian** [XinDong9511/mdseqpos_py3#2]
Hi Xindong,
I am confused by the mean_position in cistromeDB (http://cistrome.org/db/#/). The QC motif page for specific ChIP dataset demonstrated a mean_position always less than 0. Does that mean the motifs are always discovered on the left side of each peak summit?
Thanks,
Yijun

**Comment by xindongnov** [comment]
Hi Yijun,

I am not quite sure of the answer to this question either. I hypo there may be several reasons: 1) TF's motifs have their length, it's reasonable that find that the motif starts at the left of the center with a "-0.01" mean position. 2) macs2 shift and extend model might shift the center. In Cistrome DB, we did perform the extending 146 bp for TF ChIP-seq. 3) When peaks were detected(or IP from the genome), TF itself may move to the downstream of the initial binding site where the motif should be found. Hope these make sense.

Best,
Xin
